### ISSUE TITLE
测试用例错误

### ISSUE THREAD

**Issue by JayChenFE** [hcsp/refactor-to-abstract-class#2]
煎牛排的例子,测试用例的正则,此处按照原本的出题意图,应该是/s+
![image](https://user-images.githubusercontent.com/18509506/60397477-5ffc4c00-9b80-11e9-9abf-bcd0e57cec24.png)

**Comment by blindpirate** [comment]
多谢反馈！

Closed by https://github.com/hcsp/refactor-to-abstract-class/commit/204a5d52512d23e138743c9b242915a73ec150f8
